apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
data:
  tls.crt: {{ .Values.secret.tls.crt }}
  tls.key: {{ .Values.secret.tls.key }}
